receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces/default:
      receivers: [otlp]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
